version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"
      cargo-major:
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: "helm"
    directory: "/infra/helm/tyrum-core"
    schedule:
      interval: "daily"
    groups:
      helm:
        patterns:
          - "*"
