version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
