import { TyrumHttpClientError, type AgentListResult } from "@tyrum/operator-app/browser";
import type { OperatorCore } from "@tyrum/operator-app";
import * as React from "react";
import { createUniqueChannelAccountName } from "./admin-http-channel-account-name.js";
import { Badge } from "../ui/badge.js";
import { useAdminHttpClient } from "./admin-http-shared.js";

export type AdminChannelApi = NonNullable<ReturnType<typeof useAdminHttpClient>["channelConfig"]>;
export type ChannelRegistryEntry = Awaited<
  ReturnType<AdminChannelApi["listRegistry"]>
>["channels"][number];
export type ConfiguredChannelGroup = Awaited<
  ReturnType<AdminChannelApi["listChannels"]>
>["channels"][number];
export type ConfiguredChannelAccount = ConfiguredChannelGroup["accounts"][number];

export type AgentOption = {
  key: string;
  label: string;
};

export type ChannelFormState = {
  channel: string;
  accountKey: string;
  accountKeyAutoGenerated: boolean;
  configValues: Record<string, unknown>;
  secretValues: Record<string, string>;
  clearSecretKeys: Record<string, boolean>;
};

export type ChannelFieldErrors = Record<string, string[]>;

export const SECTION_LABELS: Record<string, string> = {
  credentials: "Credentials",
  access: "Access",
  delivery: "Delivery",
  advanced: "Advanced",
};

function buildAgentOptions(agents: AgentListResult["agents"]): AgentOption[] {
  return agents.map((agent) => ({
    key: agent.agent_key,
    label:
      agent.persona.name.trim().toLowerCase() === agent.agent_key.trim().toLowerCase()
        ? agent.agent_key
        : `${agent.agent_key} · ${agent.persona.name}`,
  }));
}

export async function loadAgentOptions(http: Pick<OperatorCore["admin"], "agentList" | "agents">) {
  if (http.agentList) {
    const result = await http.agentList.get({ include_default: true });
    return buildAgentOptions(result.agents);
  }
  if (http.agents) {
    const result = await http.agents.list();
    return buildAgentOptions(result.agents);
  }
  return [] as AgentOption[];
}

function readFieldValueAsString(value: unknown): string {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is string => typeof entry === "string").join("\n");
  }
  return typeof value === "string" ? value : "";
}

function readFieldValueAsBoolean(value: unknown): boolean {
  return value === true;
}

export function readFieldJsonValue(value: unknown): unknown {
  if (value === undefined || value === null || value === "") {
    return undefined;
  }
  if (typeof value === "string") {
    try {
      return JSON.parse(value) as unknown;
    } catch {
      return undefined;
    }
  }
  return value;
}

export function shouldShowField(
  field: ChannelRegistryEntry["fields"][number],
  state: ChannelFormState,
): boolean {
  if (!field.visible_when) {
    return true;
  }
  return state.configValues[field.visible_when.field_key] === field.visible_when.equals;
}

export function getFieldOptions(
  field: ChannelRegistryEntry["fields"][number],
  agentOptions: readonly AgentOption[],
) {
  if (field.option_source === "agents") {
    return agentOptions.map((agent) => ({ value: agent.key, label: agent.label }));
  }
  return field.options;
}

function getDefaultConfigValue(
  field: ChannelRegistryEntry["fields"][number],
  agentOptions: readonly AgentOption[],
): unknown {
  const inputType = field.input as string;
  if (field.default_value !== null) {
    return field.default_value;
  }
  if (field.input === "boolean") {
    return false;
  }
  if (inputType === "json") {
    return undefined;
  }
  const options = getFieldOptions(field, agentOptions);
  return options[0]?.value ?? "";
}

function readDefaultTextConfigValue(
  field: ChannelRegistryEntry["fields"][number],
  agentOptions: readonly AgentOption[],
): string {
  const defaultValue = getDefaultConfigValue(field, agentOptions);
  return typeof defaultValue === "string" ? defaultValue : "";
}

export function buildInitialFormState(input: {
  entry: ChannelRegistryEntry;
  account?: ConfiguredChannelAccount | null;
  agentOptions: readonly AgentOption[];
}): ChannelFormState {
  const configValues: Record<string, unknown> = {};
  for (const field of input.entry.fields) {
    const inputType = field.input as string;
    if (field.kind !== "config") {
      continue;
    }
    if (field.input === "boolean") {
      configValues[field.key] = readFieldValueAsBoolean(input.account?.config[field.key]);
      continue;
    }
    if (inputType === "json") {
      configValues[field.key] = readFieldJsonValue(input.account?.config[field.key]);
      continue;
    }
    const current = readFieldValueAsString(input.account?.config[field.key]);
    configValues[field.key] = current || readDefaultTextConfigValue(field, input.agentOptions);
  }

  return {
    channel: input.entry.channel,
    accountKey: input.account?.account_key ?? "",
    accountKeyAutoGenerated: !input.account,
    configValues,
    secretValues: {},
    clearSecretKeys: {},
  };
}

export function buildGeneratedChannelAccountKey(input: {
  entry: Pick<ChannelRegistryEntry, "channel" | "name">;
  groups: readonly ConfiguredChannelGroup[];
  currentAccountKey?: string | null;
}): string {
  const existingAccountKeys = input.groups
    .filter((group) => group.channel === input.entry.channel)
    .flatMap((group) => group.accounts.map((account) => account.account_key));

  return createUniqueChannelAccountName({
    preferredName: input.entry.name,
    fallbackName: input.entry.channel,
    existingAccountKeys,
    excludeAccountKey: input.currentAccountKey,
  });
}

export function buildConfigPayload(
  entry: ChannelRegistryEntry,
  state: ChannelFormState,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};
  for (const field of entry.fields) {
    const inputType = field.input as string;
    if (field.kind !== "config" || !shouldShowField(field, state)) {
      continue;
    }
    const value = state.configValues[field.key];
    if (field.input === "boolean") {
      payload[field.key] = value === true;
      continue;
    }
    if (inputType === "json") {
      if (value !== undefined) {
        payload[field.key] = value;
      }
      continue;
    }
    if (typeof value === "string" && value.trim()) {
      payload[field.key] = value;
    }
  }
  return payload;
}

export function buildSecretPayload(
  entry: ChannelRegistryEntry,
  state: ChannelFormState,
): Record<string, string> {
  const payload: Record<string, string> = {};
  for (const field of entry.fields) {
    if (field.kind !== "secret" || !shouldShowField(field, state)) {
      continue;
    }
    const value = state.secretValues[field.key]?.trim();
    if (value) {
      payload[field.key] = value;
    }
  }
  return payload;
}

export function buildClearSecretKeys(
  entry: ChannelRegistryEntry,
  state: ChannelFormState,
): string[] {
  return entry.fields
    .filter((field) => field.kind === "secret" && shouldShowField(field, state))
    .flatMap((field) => (state.clearSecretKeys[field.key] === true ? [field.key] : []));
}

export function renderFieldHelper(field: ChannelRegistryEntry["fields"][number]): React.ReactNode {
  if (!field.description && field.help_lines.length === 0) {
    return undefined;
  }
  return (
    <div className="grid gap-1">
      {field.description ? <span>{field.description}</span> : null}
      {field.help_title ? <span className="font-medium text-fg">{field.help_title}</span> : null}
      {field.help_lines.length > 0 ? (
        <div className="grid gap-0.5">
          {field.help_lines.map((line) => (
            <span key={line}>{line}</span>
          ))}
        </div>
      ) : null}
    </div>
  );
}

export function readChannelFieldErrors(error: unknown): ChannelFieldErrors {
  if (error instanceof TyrumHttpClientError && error.fieldErrors) {
    return error.fieldErrors;
  }
  return {};
}

export function clearChannelFieldError(
  fieldErrors: ChannelFieldErrors,
  fieldKey: string,
): ChannelFieldErrors {
  if (!fieldErrors[fieldKey]) {
    return fieldErrors;
  }
  const next = { ...fieldErrors };
  delete next[fieldKey];
  return next;
}

export function setChannelFieldError(
  fieldErrors: ChannelFieldErrors,
  fieldKey: string,
  message: string,
): ChannelFieldErrors {
  return {
    ...clearChannelFieldError(fieldErrors, fieldKey),
    [fieldKey]: [message],
  };
}

export function renderConfiguredBadges(
  entry: ChannelRegistryEntry | undefined,
  account: ConfiguredChannelAccount,
) {
  const configuredSecrets = new Set(account.configured_secret_keys);
  const badges: React.ReactElement[] = [];
  if (typeof account.config["agent_key"] === "string" && account.config["agent_key"].trim()) {
    badges.push(
      <Badge key="agent" variant="outline">
        Agent {String(account.config["agent_key"])}
      </Badge>,
    );
  }
  if (typeof account.config["ingress_mode"] === "string" && account.config["ingress_mode"].trim()) {
    badges.push(
      <Badge
        key="ingress_mode"
        variant={account.config["ingress_mode"] === "polling" ? "success" : "outline"}
      >
        {account.config["ingress_mode"] === "polling" ? "Polling" : "Webhook"}
      </Badge>,
    );
  }
  if (typeof account.config["pipeline_enabled"] === "boolean") {
    badges.push(
      <Badge
        key="pipeline"
        variant={account.config["pipeline_enabled"] === true ? "success" : "outline"}
      >
        Pipeline {account.config["pipeline_enabled"] === true ? "enabled" : "disabled"}
      </Badge>,
    );
  }
  if (typeof account.config["debug_logging_enabled"] === "boolean") {
    badges.push(
      <Badge
        key="debug_logging_enabled"
        variant={account.config["debug_logging_enabled"] === true ? "warning" : "outline"}
      >
        Debug logs {account.config["debug_logging_enabled"] === true ? "enabled" : "disabled"}
      </Badge>,
    );
  }
  if (
    typeof account.config["polling_status"] === "string" &&
    account.config["polling_status"].trim()
  ) {
    const status = String(account.config["polling_status"]);
    badges.push(
      <Badge
        key="polling_status"
        variant={status === "running" ? "success" : status === "error" ? "danger" : "outline"}
      >
        Poller {status}
      </Badge>,
    );
  }
  for (const field of entry?.fields ?? []) {
    if (field.kind !== "secret") {
      continue;
    }
    badges.push(
      <Badge key={field.key} variant={configuredSecrets.has(field.key) ? "success" : "outline"}>
        {field.label} {configuredSecrets.has(field.key) ? "configured" : "missing"}
      </Badge>,
    );
  }
  return badges;
}
