/**
 * Context report schema — captures what the model "saw" for a given run.
 *
 * Generated by the gateway per run and persisted for observability.
 * Exposed via `/context list` and `/context detail/:run_id`.
 */

import { z } from "zod/v4";
import { UuidSchema } from "./common.js";

export const ContextSectionSize = z
  .object({
    name: z.string(),
    byte_size: z.int().nonnegative(),
    token_estimate: z.int().nonnegative().optional(),
  })
  .strict();
export type ContextSectionSize = z.infer<typeof ContextSectionSize>;

export const WorkspaceFileEntry = z
  .object({
    path: z.string(),
    raw_bytes: z.int().nonnegative(),
    injected_bytes: z.int().nonnegative(),
    truncated: z.boolean(),
  })
  .strict();
export type WorkspaceFileEntry = z.infer<typeof WorkspaceFileEntry>;

export const ToolSchemaEntry = z
  .object({
    tool_name: z.string(),
    byte_size: z.int().nonnegative(),
  })
  .strict();
export type ToolSchemaEntry = z.infer<typeof ToolSchemaEntry>;

export const ContextReportData = z
  .object({
    system_prompt_sections: z.array(ContextSectionSize),
    workspace_files: z.array(WorkspaceFileEntry),
    tool_schemas: z.array(ToolSchemaEntry),
    history: z
      .object({
        message_count: z.int().nonnegative(),
        total_bytes: z.int().nonnegative(),
      })
      .strict(),
    tool_results: z
      .object({
        count: z.int().nonnegative(),
        total_bytes: z.int().nonnegative(),
      })
      .strict(),
    total_context_bytes: z.int().nonnegative(),
  })
  .strict();
export type ContextReportData = z.infer<typeof ContextReportData>;

export const ContextReport = z
  .object({
    report_id: UuidSchema,
    run_id: UuidSchema,
    report_json: ContextReportData,
    created_at: z.string(),
  })
  .strict();
export type ContextReport = z.infer<typeof ContextReport>;
