packages:
  - "packages/*"
  - "apps/*"

minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true

onlyBuiltDependencies:
  - better-sqlite3
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - tesseract.js
  - usocket
