// Client SDK shared entry point
export { VERSION } from "./version.js";

export { autoExecute } from "./capability.js";
export { normalizeFingerprint256 } from "./tls/fingerprint.js";
export { TyrumClient, TyrumHttpClientError, createTyrumHttpClient } from "./browser.js";
export type {
  BrowserTyrumClientOptions as TyrumClientOptions,
  BrowserTyrumHttpClientOptions,
} from "./browser.js";
export {
  DeviceIdentityError,
  buildConnectProofTranscript,
  computeDeviceIdFromPublicKeyDer,
  createBrowserLocalStorageDeviceIdentityStorage,
  createDeviceIdentity,
  formatDeviceIdentityError,
  loadOrCreateDeviceIdentity,
  signProofWithPrivateKey,
} from "./device-identity.js";
export type { DeviceIdentity, DeviceIdentityStorage } from "./device-identity.js";
export type {
  TyrumHttpAuthStrategy,
  TyrumHttpClient,
  TyrumHttpClientOperator,
  TyrumHttpErrorCode,
  TyrumHttpFetch,
  TyrumRequestOptions,
} from "./http/index.js";
export type {
  TyrumClientEvents,
  TyrumClientProtocolErrorInfo,
  TyrumClientProtocolErrorKind,
} from "./ws-client.js";
export type { CapabilityProvider, TaskExecuteContext, TaskResult } from "./capability.js";

export type {
  AuditPlansListInput,
  AuditPlansListResult,
  StatusResponse,
  UsageResponse,
  PresenceResponse,
  NodeCapabilityInspectionResponse,
  NodeActionDispatchResponse,
  PairingListResponse,
  PairingMutateResponse,
  AuthTokenListEntry,
  AuthTokenListResult,
  AuthTokenIssueInput,
  AuthTokenIssueResult,
  AuthTokenRevokeInput,
  AuthTokenRevokeResult,
  AgentListResult,
  AgentStatusResult,
  RoutingConfigGetResult,
  RoutingConfigRevisionListResult,
  RoutingConfigUpdateInput,
  RoutingConfigUpdateResult,
  RoutingConfigRevertInput,
  RoutingConfigRevertResult,
  ObservedTelegramThreadListResult,
  TelegramConnectionConfigResult,
  TelegramConnectionConfigUpdateInput,
  AuditExportResult,
  AuditVerifyInput,
  AuditVerifyResult,
  AuditForgetInput,
  AuditForgetResult,
  ContextGetResponse,
  ContextListResponse,
  ContextDetailResponse,
  ArtifactMetadataResponse,
  ArtifactBytesResult,
  HealthResponse,
  ToolRegistryListResult,
  SkillImportInput,
  UploadInput,
  McpImportInput,
  ExtensionsToggleInput,
  ExtensionsRevertInput,
} from "./http/index.js";

export type {
  Approval,
  ClientCapability,
  ExecutionAttempt,
  ExecutionRun,
  ExecutionStep,
  SessionTranscriptApprovalItem,
  SessionTranscriptItem,
  SessionTranscriptTextItem,
  SessionTranscriptTextPreview,
  SessionTranscriptTextRole,
  SessionTranscriptToolItem,
  SessionTranscriptToolStatus,
  NodePairingRequest,
  PresenceEntry,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  MemoryItemId,
  MemoryItemKind,
  MemorySensitivity,
  MemoryProvenanceSourceKind,
  MemoryProvenance,
  MemoryItem,
  MemoryItemPatch,
  MemorySearchHit,
  MemoryTombstone,
  MemoryItemFilter,
  MemoryForgetSelector,
  WsMemorySearchPayload,
  WsMemorySearchResult,
  WsMemoryListPayload,
  WsMemoryListResult,
  WsMemoryGetPayload,
  WsMemoryGetResult,
  WsMemoryUpdatePayload,
  WsMemoryUpdateResult,
  WsMemoryForgetPayload,
  WsMemoryForgetResult,
  WsMemoryExportPayload,
  WsMemoryExportResult,
  WsMemoryItemCreatedEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemConsolidatedEvent,
  WsMemoryExportCompletedEvent,
  WsSessionListItem,
  WsSessionListPayload,
  WsSessionListResult,
  WsSessionGetSession,
  WsSessionGetPayload,
  WsSessionGetResult,
  WsSessionCreatePayload,
  WsSessionCreateResult,
  WsSessionCompactPayload,
  WsSessionCompactResult,
  WsSessionDeletePayload,
  WsSessionDeleteResult,
  WsConnectRequest,
  WsConnectResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsApprovalRequest,
  WsApprovalRequestPayload,
  WsApprovalDecision,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
} from "./types.js";
