// Client SDK entry point
export const VERSION = "0.1.0";

export { TyrumClient } from "./ws-client.js";
export type {
  TyrumClientEvents,
  TyrumClientOptions,
  TyrumClientProtocolErrorInfo,
  TyrumClientProtocolErrorKind,
} from "./ws-client.js";

export { normalizeFingerprint256 } from "./tls/fingerprint.js";

export { autoExecute } from "./capability.js";
export type { CapabilityProvider, TaskExecuteContext, TaskResult } from "./capability.js";

export {
  createTyrumHttpClient,
  TyrumHttpClientError,
  type TyrumHttpAuthStrategy,
  type TyrumHttpClient,
  type TyrumHttpClientOperator,
  type TyrumHttpClientOptions,
  type TyrumHttpErrorCode,
  type TyrumHttpFetch,
  type TyrumRequestOptions,
} from "./http/index.js";

export type {
  StatusResponse,
  UsageResponse,
  PresenceResponse,
  PairingListResponse,
  PairingMutateResponse,
  AgentListResult,
  AgentStatusResult,
  RoutingConfigGetResult,
  RoutingConfigUpdateInput,
  RoutingConfigUpdateResult,
  RoutingConfigRevertInput,
  RoutingConfigRevertResult,
  AuditExportResult,
  AuditVerifyInput,
  AuditVerifyResult,
  AuditForgetInput,
  AuditForgetResult,
  ContextGetResponse,
  ContextListResponse,
  ContextDetailResponse,
  ArtifactMetadataResponse,
  ArtifactBytesResult,
  HealthResponse,
} from "./http/index.js";

export {
  buildConnectProofTranscript,
  computeDeviceIdFromPublicKeyDer,
  createBrowserLocalStorageDeviceIdentityStorage,
  createDeviceIdentity,
  createNodeFileDeviceIdentityStorage,
  DeviceIdentityError,
  formatDeviceIdentityError,
  loadOrCreateDeviceIdentity,
  signProofWithPrivateKey,
} from "./device-identity.js";
export type { DeviceIdentity, DeviceIdentityStorage } from "./device-identity.js";

export type {
  Approval,
  ClientCapability,
  ExecutionAttempt,
  ExecutionRun,
  ExecutionStep,
  NodePairingRequest,
  PresenceEntry,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  MemoryItemId,
  MemoryItemKind,
  MemorySensitivity,
  MemoryProvenanceSourceKind,
  MemoryProvenance,
  MemoryItem,
  MemoryItemPatch,
  MemorySearchHit,
  MemoryTombstone,
  MemoryItemFilter,
  MemoryForgetSelector,
  WsMemorySearchPayload,
  WsMemorySearchResult,
  WsMemoryListPayload,
  WsMemoryListResult,
  WsMemoryGetPayload,
  WsMemoryGetResult,
  WsMemoryUpdatePayload,
  WsMemoryUpdateResult,
  WsMemoryForgetPayload,
  WsMemoryForgetResult,
  WsMemoryExportPayload,
  WsMemoryExportResult,
  WsMemoryItemCreatedEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemConsolidatedEvent,
  WsMemoryExportCompletedEvent,
  WsSessionTurn,
  WsSessionListItem,
  WsSessionListPayload,
  WsSessionListResult,
  WsSessionGetSession,
  WsSessionGetPayload,
  WsSessionGetResult,
  WsSessionCreatePayload,
  WsSessionCreateResult,
  WsSessionCompactPayload,
  WsSessionCompactResult,
  WsSessionDeletePayload,
  WsSessionDeleteResult,
  WsConnectRequest,
  WsConnectResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsApprovalRequest,
  WsApprovalRequestPayload,
  WsApprovalDecision,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
} from "./types.js";
