// Client SDK shared entry point
export { VERSION } from "./version.js";

export { autoExecute } from "./capability.js";
export { normalizeFingerprint256 } from "./tls/fingerprint.js";
export { TyrumClient, TyrumHttpClientError, createTyrumHttpClient } from "./browser.js";
export {
  createTyrumAiSdkChatSessionClient,
  createTyrumAiSdkChatTransport,
  DEFAULT_TYRUM_AI_SDK_CHAT_OPERATIONS,
  supportsTyrumAiSdkChatSocket,
  TyrumAiSdkChatTransport,
} from "./ai-sdk-chat.js";
export type {
  BrowserTyrumClientOptions as TyrumClientOptions,
  BrowserTyrumHttpClientOptions,
} from "./browser.js";
export {
  DeviceIdentityError,
  buildConnectProofTranscript,
  computeDeviceIdFromPublicKeyDer,
  createBrowserLocalStorageDeviceIdentityStorage,
  createDeviceIdentity,
  formatDeviceIdentityError,
  loadOrCreateDeviceIdentity,
  signProofWithPrivateKey,
} from "./device-identity.js";
export type { DeviceIdentity, DeviceIdentityStorage } from "./device-identity.js";
export type { ChatTransport, CreateUIMessage, UIMessage, UIMessageChunk } from "ai";

export type {
  TyrumHttpAuthStrategy,
  TyrumHttpClient,
  TyrumHttpClientOperator,
  TyrumHttpErrorCode,
  TyrumHttpFetch,
  TyrumRequestOptions,
} from "./http/index.js";
export type {
  TyrumAiSdkChatOperations,
  TyrumAiSdkChatPreview,
  TyrumAiSdkChatReconnectPayload,
  TyrumAiSdkChatSession,
  TyrumAiSdkChatSessionClient,
  TyrumAiSdkChatSessionCreatePayload,
  TyrumAiSdkChatSessionDeletePayload,
  TyrumAiSdkChatSessionGetPayload,
  TyrumAiSdkChatSessionListPayload,
  TyrumAiSdkChatSessionSummary,
  TyrumAiSdkChatSendPayload,
  TyrumAiSdkChatSocket,
  TyrumAiSdkChatStreamEvent,
  TyrumAiSdkChatStreamStart,
  TyrumAiSdkChatTransportOptions,
  TyrumAiSdkChatTrigger,
} from "./ai-sdk-chat.js";

export type {
  TyrumClientEvents,
  TyrumClientDynamicSchema,
  TyrumClientProtocolErrorInfo,
  TyrumClientProtocolErrorKind,
} from "./ws-client.js";
export type { CapabilityProvider, TaskExecuteContext, TaskResult } from "./capability.js";

export type {
  AuditPlansListInput,
  AuditPlansListResult,
  StatusResponse,
  UsageResponse,
  PresenceResponse,
  NodeCapabilityInspectionResponse,
  NodeActionDispatchResponse,
  PairingListResponse,
  PairingGetResponse,
  PairingMutateResponse,
  AuthTokenListEntry,
  AuthTokenListResult,
  AuthTokenIssueInput,
  AuthTokenIssueResult,
  AuthTokenRevokeInput,
  AuthTokenRevokeResult,
  AgentListResult,
  AgentStatusResult,
  RoutingConfigGetResult,
  RoutingConfigRevisionListResult,
  RoutingConfigUpdateInput,
  RoutingConfigUpdateResult,
  RoutingConfigRevertInput,
  RoutingConfigRevertResult,
  ObservedTelegramThreadListResult,
  ChannelConfigListResult,
  ChannelConfigCreateInput,
  ChannelConfigCreateResult,
  TelegramChannelConfigUpdateInput,
  ChannelConfigUpdateResult,
  ChannelConfigDeleteResult,
  AuditExportResult,
  AuditVerifyInput,
  AuditVerifyResult,
  AuditForgetInput,
  AuditForgetResult,
  AgentCapabilitiesResult,
  ContextGetResponse,
  ContextListResponse,
  ContextDetailResponse,
  ArtifactMetadataResponse,
  ArtifactBytesResult,
  HealthResponse,
  ToolRegistryListResult,
  SkillImportInput,
  UploadInput,
  McpImportInput,
  ExtensionsToggleInput,
  ExtensionsRevertInput,
  LocationPlace,
  LocationProfile,
  LocationPlaceListResult,
  LocationPlaceMutateResult,
  LocationPlaceDeleteResult,
  LocationProfileResult,
  LocationPlaceCreateInput,
  LocationPlaceUpdateInput,
  LocationProfileUpdateInput,
} from "./http/index.js";

export type {
  Approval,
  ClientCapability,
  CheckpointSummary,
  ExecutionAttempt,
  ExecutionRun,
  ExecutionStep,
  NodePairingRequest,
  PendingApprovalState,
  PendingToolState,
  PresenceEntry,
  SessionContextState,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  MemoryItemId,
  MemoryItemKind,
  MemorySensitivity,
  MemoryProvenanceSourceKind,
  MemoryProvenance,
  MemoryItem,
  MemoryItemPatch,
  MemorySearchHit,
  MemoryTombstone,
  MemoryItemFilter,
  MemoryForgetSelector,
  WsMemorySearchPayload,
  WsMemorySearchResult,
  WsMemoryListPayload,
  WsMemoryListResult,
  WsMemoryGetPayload,
  WsMemoryGetResult,
  WsMemoryUpdatePayload,
  WsMemoryUpdateResult,
  WsMemoryForgetPayload,
  WsMemoryForgetResult,
  WsMemoryExportPayload,
  WsMemoryExportResult,
  WsMemoryItemCreatedEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemConsolidatedEvent,
  WsMemoryExportCompletedEvent,
  WsLocationBeaconPayload,
  WsLocationBeaconResult,
  WsConnectRequest,
  WsConnectResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
} from "./types.js";
