import {
  buildConnectProofTranscript,
  computeDeviceIdFromPublicKeyDer,
  createDeviceIdentity,
  DeviceIdentityError,
  formatDeviceIdentityError,
  loadOrCreateDeviceIdentity,
  signProofWithPrivateKey,
  type DeviceIdentity,
  type DeviceIdentityStorage,
} from "./device-identity.js";
import { createNodeFileDeviceIdentityStorage } from "./device-identity-node.js";
import {
  createTyrumHttpClient,
  TyrumHttpClientError,
  type TyrumHttpAuthStrategy,
  type TyrumHttpClient,
  type TyrumHttpClientOperator,
  type TyrumHttpClientOptions as NodeTyrumHttpClientOptions,
  type TyrumHttpErrorCode,
  type TyrumHttpFetch,
  type TyrumRequestOptions,
} from "./http/index.js";
import {
  createPinnedNodeTransportState,
  createPinnedNodeWebSocket,
  destroyPinnedNodeDispatcher,
  type NodePinnedTlsOptions,
  type NodePinnedTransportState,
  type NodePinnedWebSocketOptions,
} from "./node/pinned-transport.js";
import { normalizeFingerprint256 } from "./tls/fingerprint.js";
import {
  TyrumClient,
  type TyrumClientEvents,
  type TyrumClientOptions as NodeTyrumClientOptions,
  type TyrumClientProtocolErrorInfo,
  type TyrumClientProtocolErrorKind,
} from "./ws-client.js";
import { VERSION } from "./version.js";

export { autoExecute } from "./capability.js";
export type { CapabilityProvider, TaskExecuteContext, TaskResult } from "./capability.js";
export type {
  AuditPlansListInput,
  AuditPlansListResult,
  StatusResponse,
  UsageResponse,
  PresenceResponse,
  PairingListResponse,
  PairingMutateResponse,
  AuthTokenListEntry,
  AuthTokenListResult,
  AuthTokenIssueInput,
  AuthTokenIssueResult,
  AuthTokenRevokeInput,
  AuthTokenRevokeResult,
  AgentListResult,
  AgentStatusResult,
  RoutingConfigGetResult,
  RoutingConfigUpdateInput,
  RoutingConfigUpdateResult,
  RoutingConfigRevertInput,
  RoutingConfigRevertResult,
  AuditExportResult,
  AuditVerifyInput,
  AuditVerifyResult,
  AuditForgetInput,
  AuditForgetResult,
  ContextGetResponse,
  ContextListResponse,
  ContextDetailResponse,
  ArtifactMetadataResponse,
  ArtifactBytesResult,
  HealthResponse,
  SkillImportInput,
  UploadInput,
  McpImportInput,
  ExtensionsToggleInput,
  ExtensionsRevertInput,
} from "./http/index.js";
export type {
  Approval,
  ClientCapability,
  ExecutionAttempt,
  ExecutionRun,
  ExecutionStep,
  SessionTranscriptApprovalItem,
  SessionTranscriptItem,
  SessionTranscriptTextItem,
  SessionTranscriptTextPreview,
  SessionTranscriptTextRole,
  SessionTranscriptToolItem,
  SessionTranscriptToolStatus,
  NodePairingRequest,
  PresenceEntry,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  MemoryItemId,
  MemoryItemKind,
  MemorySensitivity,
  MemoryProvenanceSourceKind,
  MemoryProvenance,
  MemoryItem,
  MemoryItemPatch,
  MemorySearchHit,
  MemoryTombstone,
  MemoryItemFilter,
  MemoryForgetSelector,
  WsMemorySearchPayload,
  WsMemorySearchResult,
  WsMemoryListPayload,
  WsMemoryListResult,
  WsMemoryGetPayload,
  WsMemoryGetResult,
  WsMemoryUpdatePayload,
  WsMemoryUpdateResult,
  WsMemoryForgetPayload,
  WsMemoryForgetResult,
  WsMemoryExportPayload,
  WsMemoryExportResult,
  WsMemoryItemCreatedEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemConsolidatedEvent,
  WsMemoryExportCompletedEvent,
  WsSessionListItem,
  WsSessionListPayload,
  WsSessionListResult,
  WsSessionGetSession,
  WsSessionGetPayload,
  WsSessionGetResult,
  WsSessionCreatePayload,
  WsSessionCreateResult,
  WsSessionCompactPayload,
  WsSessionCompactResult,
  WsSessionDeletePayload,
  WsSessionDeleteResult,
  WsConnectRequest,
  WsConnectResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsApprovalRequest,
  WsApprovalRequestPayload,
  WsApprovalDecision,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
} from "./types.js";

export {
  TyrumClient,
  normalizeFingerprint256,
  buildConnectProofTranscript,
  computeDeviceIdFromPublicKeyDer,
  createDeviceIdentity,
  createNodeFileDeviceIdentityStorage,
  createPinnedNodeTransportState,
  createPinnedNodeWebSocket,
  destroyPinnedNodeDispatcher,
  DeviceIdentityError,
  formatDeviceIdentityError,
  loadOrCreateDeviceIdentity,
  createTyrumHttpClient,
  TyrumHttpClientError,
  signProofWithPrivateKey,
};
export type {
  DeviceIdentity,
  DeviceIdentityStorage,
  NodePinnedTlsOptions,
  NodePinnedTransportState,
  NodePinnedWebSocketOptions,
  NodeTyrumClientOptions,
  NodeTyrumHttpClientOptions,
  TyrumClientEvents,
  TyrumClientProtocolErrorInfo,
  TyrumClientProtocolErrorKind,
  TyrumHttpAuthStrategy,
  TyrumHttpClient,
  TyrumHttpClientOperator,
  TyrumHttpErrorCode,
  TyrumHttpFetch,
  TyrumRequestOptions,
};
export { VERSION };
