/**
 * Convenience re-exports from @tyrum/schemas so consumers of @tyrum/client
 * don't need a direct dependency on the schemas package for common types.
 */

export type {
  ClientCapability,
  PeerRole,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  WS_PROTOCOL_REV,
  CapabilityName,
  CapabilityDescriptor,
  WsConnectInitPayload,
  WsConnectInitRequest,
  WsConnectInitResult,
  WsConnectProofPayload,
  WsConnectProofRequest,
  WsConnectProofResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsApprovalRequest,
  WsApprovalRequestPayload,
  WsApprovalDecision,
  WsSessionSendPayload,
  WsSessionSendRequest,
  WsSessionSendResult,
  WsPairingApprovePayload,
  WsPairingApproveRequest,
  WsPairingApproveResult,
  WsPairingDenyPayload,
  WsPairingDenyRequest,
  WsPairingDenyResult,
  WsPairingRevokePayload,
  WsPairingRevokeRequest,
  WsPairingRevokeResult,
  WsPairingApprovedEvent,
  WsPairingApprovedPayload,
  WsWorkflowRunPayload,
  WsWorkflowRunRequest,
  WsWorkflowRunResult,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
} from "@tyrum/schemas";
