/**
 * Convenience re-exports from @tyrum/schemas so consumers of @tyrum/client
 * don't need a direct dependency on the schemas package for common types.
 */

export type {
  ClientCapability,
  Approval,
  CheckpointSummary,
  PendingApprovalState,
  PendingToolState,
  SessionContextState,
  WsError,
  WsRequestEnvelope,
  WsResponseEnvelope,
  WsEventEnvelope,
  WsMessageEnvelope,
  MemoryItemId,
  MemoryItemKind,
  MemorySensitivity,
  MemoryProvenanceSourceKind,
  MemoryProvenance,
  MemoryItem,
  MemoryTombstone,
  WsLocationBeaconPayload,
  WsLocationBeaconResult,
  WsConnectRequest,
  WsConnectResult,
  WsTaskExecuteRequest,
  WsTaskExecutePayload,
  WsTaskExecuteResult,
  WsPlanUpdateEvent,
  WsPlanUpdatePayload,
  WsErrorEvent,
  WsErrorEventPayload,
  ActionPrimitive,
  ActionPrimitiveKind,
  PlanRequest,
  PlanResponse,
  ExecutionRun,
  ExecutionStep,
  ExecutionAttempt,
  NodePairingRequest,
  PresenceEntry,
} from "@tyrum/schemas";
