import { z } from "zod";
import {
  WsApprovalListResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalRequestResponseErrEnvelope,
  WsApprovalRequestResponseOkEnvelope,
  WsApprovalResolveResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
} from "./approvals.js";
import {
  WsCapabilityReadyResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
} from "./capability-ready.js";
import {
  WsConnectInitResponseErrEnvelope,
  WsConnectInitResponseOkEnvelope,
  WsConnectProofResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsPingResponseErrEnvelope,
  WsPingResponseOkEnvelope,
} from "./connect.js";
import {
  WsAttemptEvidenceResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsRunListResponseErrEnvelope,
  WsRunListResponseOkEnvelope,
  WsTaskExecuteResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
} from "./execution.js";
import {
  WsPairingApproveResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingDenyResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingRevokeResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
} from "./pairing.js";
import {
  WsLocationBeaconResponseErrEnvelope,
  WsLocationBeaconResponseOkEnvelope,
} from "./location.js";
import {
  WsPresenceBeaconResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
} from "./presence.js";
import {
  WsSessionCompactResponseErrEnvelope,
  WsSessionCompactResponseOkEnvelope,
  WsSessionCreateResponseErrEnvelope,
  WsSessionCreateResponseOkEnvelope,
  WsSessionDeleteResponseErrEnvelope,
  WsSessionDeleteResponseOkEnvelope,
  WsSessionGetResponseErrEnvelope,
  WsSessionGetResponseOkEnvelope,
  WsSessionListResponseErrEnvelope,
  WsSessionListResponseOkEnvelope,
  WsSessionSendResponseErrEnvelope,
  WsSessionSendResponseOkEnvelope,
} from "./session.js";
import {
  WsSubagentCloseResponseErrEnvelope,
  WsSubagentCloseResponseOkEnvelope,
  WsSubagentGetResponseErrEnvelope,
  WsSubagentGetResponseOkEnvelope,
  WsSubagentListResponseErrEnvelope,
  WsSubagentListResponseOkEnvelope,
  WsSubagentSendResponseErrEnvelope,
  WsSubagentSendResponseOkEnvelope,
  WsSubagentSpawnResponseErrEnvelope,
  WsSubagentSpawnResponseOkEnvelope,
} from "./subagent.js";
import {
  WsWorkflowCancelResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
} from "./workflow.js";
import {
  WsWorkArtifactCreateResponseErrEnvelope,
  WsWorkArtifactCreateResponseOkEnvelope,
  WsWorkArtifactGetResponseErrEnvelope,
  WsWorkArtifactGetResponseOkEnvelope,
  WsWorkArtifactListResponseErrEnvelope,
  WsWorkArtifactListResponseOkEnvelope,
  WsWorkCreateResponseErrEnvelope,
  WsWorkCreateResponseOkEnvelope,
  WsWorkDecisionCreateResponseErrEnvelope,
  WsWorkDecisionCreateResponseOkEnvelope,
  WsWorkDecisionGetResponseErrEnvelope,
  WsWorkDecisionGetResponseOkEnvelope,
  WsWorkDecisionListResponseErrEnvelope,
  WsWorkDecisionListResponseOkEnvelope,
  WsWorkGetResponseErrEnvelope,
  WsWorkGetResponseOkEnvelope,
  WsWorkLinkCreateResponseErrEnvelope,
  WsWorkLinkCreateResponseOkEnvelope,
  WsWorkLinkListResponseErrEnvelope,
  WsWorkLinkListResponseOkEnvelope,
  WsWorkListResponseErrEnvelope,
  WsWorkListResponseOkEnvelope,
  WsWorkSignalCreateResponseErrEnvelope,
  WsWorkSignalCreateResponseOkEnvelope,
  WsWorkSignalGetResponseErrEnvelope,
  WsWorkSignalGetResponseOkEnvelope,
  WsWorkSignalListResponseErrEnvelope,
  WsWorkSignalListResponseOkEnvelope,
  WsWorkSignalUpdateResponseErrEnvelope,
  WsWorkSignalUpdateResponseOkEnvelope,
  WsWorkStateKvGetResponseErrEnvelope,
  WsWorkStateKvGetResponseOkEnvelope,
  WsWorkStateKvListResponseErrEnvelope,
  WsWorkStateKvListResponseOkEnvelope,
  WsWorkStateKvSetResponseErrEnvelope,
  WsWorkStateKvSetResponseOkEnvelope,
  WsWorkTransitionResponseErrEnvelope,
  WsWorkTransitionResponseOkEnvelope,
  WsWorkUpdateResponseErrEnvelope,
  WsWorkUpdateResponseOkEnvelope,
} from "./work.js";

export const WsResponse = z.union([
  WsConnectInitResponseOkEnvelope,
  WsConnectInitResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectProofResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsConnectResponseErrEnvelope,
  WsSessionSendResponseOkEnvelope,
  WsSessionSendResponseErrEnvelope,
  WsSessionListResponseOkEnvelope,
  WsSessionListResponseErrEnvelope,
  WsSessionGetResponseOkEnvelope,
  WsSessionGetResponseErrEnvelope,
  WsSessionCreateResponseOkEnvelope,
  WsSessionCreateResponseErrEnvelope,
  WsSessionCompactResponseOkEnvelope,
  WsSessionCompactResponseErrEnvelope,
  WsSessionDeleteResponseOkEnvelope,
  WsSessionDeleteResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowCancelResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingApproveResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingDenyResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
  WsPairingRevokeResponseErrEnvelope,
  WsLocationBeaconResponseOkEnvelope,
  WsLocationBeaconResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
  WsPresenceBeaconResponseErrEnvelope,
  WsPingResponseOkEnvelope,
  WsPingResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
  WsCapabilityReadyResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsAttemptEvidenceResponseErrEnvelope,
  WsRunListResponseOkEnvelope,
  WsRunListResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
  WsTaskExecuteResponseErrEnvelope,
  WsApprovalRequestResponseOkEnvelope,
  WsApprovalRequestResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalListResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
  WsApprovalResolveResponseErrEnvelope,
  WsSubagentSpawnResponseOkEnvelope,
  WsSubagentSpawnResponseErrEnvelope,
  WsSubagentListResponseOkEnvelope,
  WsSubagentListResponseErrEnvelope,
  WsSubagentGetResponseOkEnvelope,
  WsSubagentGetResponseErrEnvelope,
  WsSubagentSendResponseOkEnvelope,
  WsSubagentSendResponseErrEnvelope,
  WsSubagentCloseResponseOkEnvelope,
  WsSubagentCloseResponseErrEnvelope,
  WsWorkListResponseOkEnvelope,
  WsWorkListResponseErrEnvelope,
  WsWorkGetResponseOkEnvelope,
  WsWorkGetResponseErrEnvelope,
  WsWorkCreateResponseOkEnvelope,
  WsWorkCreateResponseErrEnvelope,
  WsWorkUpdateResponseOkEnvelope,
  WsWorkUpdateResponseErrEnvelope,
  WsWorkTransitionResponseOkEnvelope,
  WsWorkTransitionResponseErrEnvelope,
  WsWorkLinkCreateResponseOkEnvelope,
  WsWorkLinkCreateResponseErrEnvelope,
  WsWorkLinkListResponseOkEnvelope,
  WsWorkLinkListResponseErrEnvelope,
  WsWorkArtifactListResponseOkEnvelope,
  WsWorkArtifactListResponseErrEnvelope,
  WsWorkArtifactGetResponseOkEnvelope,
  WsWorkArtifactGetResponseErrEnvelope,
  WsWorkArtifactCreateResponseOkEnvelope,
  WsWorkArtifactCreateResponseErrEnvelope,
  WsWorkDecisionListResponseOkEnvelope,
  WsWorkDecisionListResponseErrEnvelope,
  WsWorkDecisionGetResponseOkEnvelope,
  WsWorkDecisionGetResponseErrEnvelope,
  WsWorkDecisionCreateResponseOkEnvelope,
  WsWorkDecisionCreateResponseErrEnvelope,
  WsWorkSignalListResponseOkEnvelope,
  WsWorkSignalListResponseErrEnvelope,
  WsWorkSignalGetResponseOkEnvelope,
  WsWorkSignalGetResponseErrEnvelope,
  WsWorkSignalCreateResponseOkEnvelope,
  WsWorkSignalCreateResponseErrEnvelope,
  WsWorkSignalUpdateResponseOkEnvelope,
  WsWorkSignalUpdateResponseErrEnvelope,
  WsWorkStateKvGetResponseOkEnvelope,
  WsWorkStateKvGetResponseErrEnvelope,
  WsWorkStateKvListResponseOkEnvelope,
  WsWorkStateKvListResponseErrEnvelope,
  WsWorkStateKvSetResponseOkEnvelope,
  WsWorkStateKvSetResponseErrEnvelope,
]);
export type WsResponse = z.infer<typeof WsResponse>;
