import { z } from "zod";
import {
  WsApprovalListRequest,
  WsApprovalRequest,
  WsApprovalRequestedEvent,
  WsApprovalResolveRequest,
  WsApprovalResolvedEvent,
} from "./approvals.js";
import { WsCapabilityReadyEvent, WsCapabilityReadyRequest } from "./capability-ready.js";
import {
  WsConnectInitRequest,
  WsConnectProofRequest,
  WsConnectRequest,
  WsPingRequest,
} from "./connect.js";
import {
  WsArtifactAttachedEvent,
  WsArtifactCreatedEvent,
  WsArtifactFetchedEvent,
  WsAttemptEvidenceEvent,
  WsAttemptEvidenceRequest,
  WsRunListRequest,
  WsAttemptUpdatedEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsChannelQueueOverflowEvent,
  WsContextReportCreatedEvent,
  WsErrorEvent,
  WsPlanUpdateEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPolicyOverrideRevokedEvent,
  WsProviderUsagePolledEvent,
  WsRoutingConfigUpdatedEvent,
  WsRunCompletedEvent,
  WsRunCancelledEvent,
  WsRunFailedEvent,
  WsRunPausedEvent,
  WsRunQueuedEvent,
  WsRunResumedEvent,
  WsRunStartedEvent,
  WsToolLifecycleEvent,
  WsRunUpdatedEvent,
  WsStepUpdatedEvent,
  WsTaskExecuteRequest,
  WsUsageSnapshotEvent,
} from "./execution.js";
import {
  WsMemoryCreateRequest,
  WsMemoryDeleteRequest,
  WsMemoryExportCompletedEvent,
  WsMemoryExportRequest,
  WsMemoryForgetRequest,
  WsMemoryItemConsolidatedEvent,
  WsMemoryItemCreatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryListRequest,
  WsMemoryGetRequest,
  WsMemorySearchRequest,
  WsMemoryUpdateRequest,
} from "./memory.js";
import {
  WsPairingApproveRequest,
  WsPairingApprovedEvent,
  WsPairingDenyRequest,
  WsPairingRequestedEvent,
  WsPairingResolvedEvent,
  WsPairingRevokeRequest,
} from "./pairing.js";
import {
  WsPresenceBeaconRequest,
  WsPresencePrunedEvent,
  WsPresenceUpsertedEvent,
} from "./presence.js";
import {
  WsDeliveryReceiptEvent,
  WsFormattingFallbackEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsSessionCompactRequest,
  WsSessionCreateRequest,
  WsSessionDeleteRequest,
  WsSessionGetRequest,
  WsSessionListRequest,
  WsSessionSendRequest,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
  WsCommandExecuteRequest,
} from "./session.js";
import {
  WsSubagentCloseRequest,
  WsSubagentClosedEvent,
  WsSubagentGetRequest,
  WsSubagentListRequest,
  WsSubagentOutputEvent,
  WsSubagentSendRequest,
  WsSubagentSpawnedEvent,
  WsSubagentSpawnRequest,
  WsSubagentUpdatedEvent,
} from "./subagent.js";
import { WsResponse } from "./unions-response.js";
import {
  WsWorkflowCancelRequest,
  WsWorkflowResumeRequest,
  WsWorkflowRunRequest,
} from "./workflow.js";
import {
  WsWorkArtifactCreateRequest,
  WsWorkArtifactCreatedEvent,
  WsWorkArtifactGetRequest,
  WsWorkArtifactListRequest,
  WsWorkCreateRequest,
  WsWorkDecisionCreateRequest,
  WsWorkDecisionCreatedEvent,
  WsWorkDecisionGetRequest,
  WsWorkDecisionListRequest,
  WsWorkGetRequest,
  WsWorkItemBlockedEvent,
  WsWorkItemCancelledEvent,
  WsWorkItemCompletedEvent,
  WsWorkItemFailedEvent,
  WsWorkItemCreatedEvent,
  WsWorkItemUpdatedEvent,
  WsWorkLinkCreateRequest,
  WsWorkLinkCreatedEvent,
  WsWorkLinkListRequest,
  WsWorkListRequest,
  WsWorkSignalCreateRequest,
  WsWorkSignalCreatedEvent,
  WsWorkSignalUpdatedEvent,
  WsWorkSignalFiredEvent,
  WsWorkSignalGetRequest,
  WsWorkSignalListRequest,
  WsWorkSignalUpdateRequest,
  WsWorkStateKvGetRequest,
  WsWorkStateKvListRequest,
  WsWorkStateKvSetRequest,
  WsWorkStateKvUpdatedEvent,
  WsWorkTaskCompletedEvent,
  WsWorkTaskLeasedEvent,
  WsWorkTaskPausedEvent,
  WsWorkTaskStartedEvent,
  WsWorkTransitionRequest,
  WsWorkUpdateRequest,
} from "./work.js";

export * from "./unions-response.js";

export const WsRequest = z.discriminatedUnion("type", [
  WsConnectInitRequest,
  WsConnectProofRequest,
  WsConnectRequest,
  WsPresenceBeaconRequest,
  WsPingRequest,
  WsSessionSendRequest,
  WsSessionListRequest,
  WsSessionGetRequest,
  WsSessionCreateRequest,
  WsSessionCompactRequest,
  WsSessionDeleteRequest,
  WsCommandExecuteRequest,
  WsWorkflowRunRequest,
  WsWorkflowResumeRequest,
  WsWorkflowCancelRequest,
  WsPairingRevokeRequest,
  WsPairingApproveRequest,
  WsPairingDenyRequest,
  WsCapabilityReadyRequest,
  WsTaskExecuteRequest,
  WsAttemptEvidenceRequest,
  WsRunListRequest,
  WsApprovalRequest,
  WsApprovalListRequest,
  WsApprovalResolveRequest,
  WsSubagentSpawnRequest,
  WsSubagentListRequest,
  WsSubagentGetRequest,
  WsSubagentSendRequest,
  WsSubagentCloseRequest,
  WsWorkListRequest,
  WsWorkGetRequest,
  WsWorkCreateRequest,
  WsWorkUpdateRequest,
  WsWorkTransitionRequest,
  WsWorkLinkCreateRequest,
  WsWorkLinkListRequest,
  WsWorkArtifactListRequest,
  WsWorkArtifactGetRequest,
  WsWorkArtifactCreateRequest,
  WsWorkDecisionListRequest,
  WsWorkDecisionGetRequest,
  WsWorkDecisionCreateRequest,
  WsWorkSignalListRequest,
  WsWorkSignalGetRequest,
  WsWorkSignalCreateRequest,
  WsWorkSignalUpdateRequest,
  WsWorkStateKvGetRequest,
  WsWorkStateKvListRequest,
  WsWorkStateKvSetRequest,
  WsMemorySearchRequest,
  WsMemoryListRequest,
  WsMemoryGetRequest,
  WsMemoryCreateRequest,
  WsMemoryUpdateRequest,
  WsMemoryDeleteRequest,
  WsMemoryForgetRequest,
  WsMemoryExportRequest,
]);
export type WsRequest = z.infer<typeof WsRequest>;

export const WsEvent = z.discriminatedUnion("type", [
  WsPlanUpdateEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsApprovalRequestedEvent,
  WsApprovalResolvedEvent,
  WsRunUpdatedEvent,
  WsRunQueuedEvent,
  WsRunStartedEvent,
  WsRunPausedEvent,
  WsRunResumedEvent,
  WsRunCompletedEvent,
  WsRunFailedEvent,
  WsRunCancelledEvent,
  WsStepUpdatedEvent,
  WsAttemptUpdatedEvent,
  WsArtifactCreatedEvent,
  WsArtifactAttachedEvent,
  WsArtifactFetchedEvent,
  WsCapabilityReadyEvent,
  WsAttemptEvidenceEvent,
  WsPairingRequestedEvent,
  WsPairingApprovedEvent,
  WsPairingResolvedEvent,
  WsPresenceUpsertedEvent,
  WsPresencePrunedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideRevokedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsToolLifecycleEvent,
  WsChannelQueueOverflowEvent,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsFormattingFallbackEvent,
  WsDeliveryReceiptEvent,
  WsUsageSnapshotEvent,
  WsProviderUsagePolledEvent,
  WsContextReportCreatedEvent,
  WsRoutingConfigUpdatedEvent,
  WsWorkItemCreatedEvent,
  WsWorkItemUpdatedEvent,
  WsWorkItemBlockedEvent,
  WsWorkItemCompletedEvent,
  WsWorkItemFailedEvent,
  WsWorkItemCancelledEvent,
  WsWorkLinkCreatedEvent,
  WsWorkTaskLeasedEvent,
  WsWorkTaskStartedEvent,
  WsWorkTaskPausedEvent,
  WsWorkTaskCompletedEvent,
  WsWorkArtifactCreatedEvent,
  WsWorkDecisionCreatedEvent,
  WsWorkSignalCreatedEvent,
  WsWorkSignalUpdatedEvent,
  WsWorkSignalFiredEvent,
  WsWorkStateKvUpdatedEvent,
  WsSubagentSpawnedEvent,
  WsSubagentUpdatedEvent,
  WsSubagentClosedEvent,
  WsSubagentOutputEvent,
  WsMemoryItemCreatedEvent,
  WsMemoryItemUpdatedEvent,
  WsMemoryItemDeletedEvent,
  WsMemoryItemForgottenEvent,
  WsMemoryItemConsolidatedEvent,
  WsMemoryExportCompletedEvent,
  WsErrorEvent,
]);
export type WsEvent = z.infer<typeof WsEvent>;

export const WsMessage = z.union([WsRequest, WsResponse, WsEvent]);
export type WsMessage = z.infer<typeof WsMessage>;
