import { z } from "zod";
import {
  WsApprovalListRequest,
  WsApprovalListResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalRequest,
  WsApprovalRequestResponseErrEnvelope,
  WsApprovalRequestResponseOkEnvelope,
  WsApprovalRequestedEvent,
  WsApprovalResolveRequest,
  WsApprovalResolveResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
  WsApprovalResolvedEvent,
} from "./approvals.js";
import {
  WsCapabilityReadyEvent,
  WsCapabilityReadyRequest,
  WsCapabilityReadyResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
} from "./capability-ready.js";
import {
  WsConnectInitRequest,
  WsConnectInitResponseErrEnvelope,
  WsConnectInitResponseOkEnvelope,
  WsConnectProofRequest,
  WsConnectProofResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectRequest,
  WsConnectResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsPingRequest,
  WsPingResponseErrEnvelope,
  WsPingResponseOkEnvelope,
} from "./connect.js";
import {
  WsArtifactAttachedEvent,
  WsArtifactCreatedEvent,
  WsArtifactFetchedEvent,
  WsAttemptEvidenceEvent,
  WsAttemptEvidenceRequest,
  WsAttemptEvidenceResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsAttemptUpdatedEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsChannelQueueOverflowEvent,
  WsContextReportCreatedEvent,
  WsErrorEvent,
  WsPlanUpdateEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPolicyOverrideRevokedEvent,
  WsProviderUsagePolledEvent,
  WsRoutingConfigUpdatedEvent,
  WsRunCancelledEvent,
  WsRunPausedEvent,
  WsRunResumedEvent,
  WsRunUpdatedEvent,
  WsStepUpdatedEvent,
  WsTaskExecuteRequest,
  WsTaskExecuteResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
  WsUsageSnapshotEvent,
} from "./execution.js";
import {
  WsPairingApproveRequest,
  WsPairingApproveResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingApprovedEvent,
  WsPairingDenyRequest,
  WsPairingDenyResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingRequestedEvent,
  WsPairingResolvedEvent,
  WsPairingRevokeRequest,
  WsPairingRevokeResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
} from "./pairing.js";
import {
  WsPresenceBeaconRequest,
  WsPresenceBeaconResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
  WsPresencePrunedEvent,
  WsPresenceUpsertedEvent,
} from "./presence.js";
import {
  WsDeliveryReceiptEvent,
  WsFormattingFallbackEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsSessionSendRequest,
  WsSessionSendResponseErrEnvelope,
  WsSessionSendResponseOkEnvelope,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
  WsCommandExecuteRequest,
} from "./session.js";
import {
  WsWorkflowCancelRequest,
  WsWorkflowCancelResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowResumeRequest,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowRunRequest,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
} from "./workflow.js";

export const WsResponse = z.union([
  WsConnectInitResponseOkEnvelope,
  WsConnectInitResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectProofResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsConnectResponseErrEnvelope,
  WsSessionSendResponseOkEnvelope,
  WsSessionSendResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowCancelResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingApproveResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingDenyResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
  WsPairingRevokeResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
  WsPresenceBeaconResponseErrEnvelope,
  WsPingResponseOkEnvelope,
  WsPingResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
  WsCapabilityReadyResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsAttemptEvidenceResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
  WsTaskExecuteResponseErrEnvelope,
  WsApprovalRequestResponseOkEnvelope,
  WsApprovalRequestResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalListResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
  WsApprovalResolveResponseErrEnvelope,
]);
export type WsResponse = z.infer<typeof WsResponse>;

export const WsRequest = z.discriminatedUnion("type", [
  WsConnectInitRequest,
  WsConnectProofRequest,
  WsConnectRequest,
  WsPresenceBeaconRequest,
  WsPingRequest,
  WsSessionSendRequest,
  WsCommandExecuteRequest,
  WsWorkflowRunRequest,
  WsWorkflowResumeRequest,
  WsWorkflowCancelRequest,
  WsPairingRevokeRequest,
  WsPairingApproveRequest,
  WsPairingDenyRequest,
  WsCapabilityReadyRequest,
  WsTaskExecuteRequest,
  WsAttemptEvidenceRequest,
  WsApprovalRequest,
  WsApprovalListRequest,
  WsApprovalResolveRequest,
]);
export type WsRequest = z.infer<typeof WsRequest>;

export const WsEvent = z.discriminatedUnion("type", [
  WsPlanUpdateEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsApprovalRequestedEvent,
  WsApprovalResolvedEvent,
  WsRunUpdatedEvent,
  WsRunPausedEvent,
  WsRunResumedEvent,
  WsRunCancelledEvent,
  WsStepUpdatedEvent,
  WsAttemptUpdatedEvent,
  WsArtifactCreatedEvent,
  WsArtifactAttachedEvent,
  WsArtifactFetchedEvent,
  WsCapabilityReadyEvent,
  WsAttemptEvidenceEvent,
  WsPairingRequestedEvent,
  WsPairingApprovedEvent,
  WsPairingResolvedEvent,
  WsPresenceUpsertedEvent,
  WsPresencePrunedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideRevokedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsChannelQueueOverflowEvent,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsFormattingFallbackEvent,
  WsDeliveryReceiptEvent,
  WsUsageSnapshotEvent,
  WsProviderUsagePolledEvent,
  WsContextReportCreatedEvent,
  WsRoutingConfigUpdatedEvent,
  WsErrorEvent,
]);
export type WsEvent = z.infer<typeof WsEvent>;

export const WsMessage = z.union([WsRequest, WsResponse, WsEvent]);
export type WsMessage = z.infer<typeof WsMessage>;
