server:
  http_listen_port: 3200
  grpc_listen_port: 4317
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        http: {}
        grpc: {}

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  max_block_duration: 5m
  trace_idle_period: 30s

querier:
  frontend_worker:
    frontend_address: tempo:9095

query_frontend:
  search:
    concurrent_jobs: 200
    target_bytes_per_job: 10000000

compactor:
  compaction:
    block_retention: 48h
  ring:
    kvstore:
      store: inmemory
  working_directory: /var/tempo/compactor

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
