export type { DashboardPageProps } from "./components/pages/dashboard-page.js";
export { DashboardPage } from "./components/pages/dashboard-page.js";
export { AgentsPage } from "./components/pages/agents-page.js";
export { ApprovalsPage } from "./components/pages/approvals-page.js";
export type { WorkBoardPageProps } from "./components/pages/workboard-page.js";
export { WorkBoardPage } from "./components/pages/workboard-page.js";
export { ConnectPage } from "./components/pages/connect-page.js";
export { PairingPage } from "./components/pages/pairing-page.js";
export { DesktopEnvironmentsPage } from "./components/pages/desktop-environments-page.js";
export type { ConfigurePageProps } from "./components/pages/configure-page.js";
export { ConfigurePage } from "./components/pages/configure-page.js";
export { AiSdkChatPage } from "./components/pages/chat-page-ai-sdk.js";
export { ExtensionsPage } from "./components/pages/extensions-page.js";
export { MemoryPage } from "./components/pages/memory-page.js";
export { FirstRunOnboardingPage } from "./components/pages/first-run-onboarding.js";
export { SettingsPage } from "./components/pages/settings-page.js";
export { NodeConfigPage } from "./components/pages/node-config/node-config-page.js";
