import type { TyrumClient, TyrumHttpClientOperator } from "@tyrum/transport-sdk/browser";

export type OperatorWsClient = Pick<
  TyrumClient,
  | "connected"
  | "connect"
  | "disconnect"
  | "on"
  | "off"
  | "requestDynamic"
  | "onDynamicEvent"
  | "offDynamicEvent"
  | "respondTaskExecute"
  | "approvalList"
  | "runList"
  | "approvalResolve"
  | "commandExecute"
  | "ping"
  | "workflowRun"
  | "workflowResume"
  | "workflowCancel"
  | "pairingApprove"
  | "pairingDeny"
  | "pairingRevoke"
  | "presenceBeacon"
  | "capabilityReady"
  | "attemptEvidence"
  | "workList"
  | "workGet"
  | "workCreate"
  | "workUpdate"
  | "workDelete"
  | "workTransition"
  | "workPause"
  | "workResume"
  | "workLinkCreate"
  | "workLinkList"
  | "workArtifactList"
  | "workArtifactGet"
  | "workArtifactCreate"
  | "workDecisionList"
  | "workDecisionGet"
  | "workDecisionCreate"
  | "workSignalList"
  | "workSignalGet"
  | "workSignalCreate"
  | "workSignalUpdate"
  | "workStateKvGet"
  | "workStateKvList"
  | "workStateKvSet"
  | "subagentSpawn"
  | "subagentList"
  | "subagentGet"
  | "subagentSend"
  | "subagentClose"
>;

export type OperatorHttpClient = TyrumHttpClientOperator;
