export function printCliHelp(): void {
  console.log(
    [
      "tyrum-cli (operator CLI)",
      "",
      "Usage:",
      "  tyrum-cli --help",
      "  tyrum-cli --version",
      "  tyrum-cli config show",
      "  tyrum-cli config set --gateway-url <url> --token <token> [--tls-fingerprint256 <hex>] [--tls-allow-self-signed]",
      "  tyrum-cli identity show",
      "  tyrum-cli identity init",
      "  tyrum-cli elevated-mode enter [--ttl-seconds <n>]",
      "  tyrum-cli elevated-mode status",
      "  tyrum-cli elevated-mode exit",
      "  tyrum-cli approvals list [--limit <n>]",
      "  tyrum-cli approvals resolve --approval-id <id> --decision <approved|denied> [--reason <text>]",
      "  tyrum-cli workflow run --key <key> --steps <json> [--lane <lane>]",
      "  tyrum-cli workflow resume --token <resume-token>",
      "  tyrum-cli workflow cancel --run-id <run-id> [--reason <text>]",
      "  tyrum-cli pairing approve --pairing-id <id> --trust-level <local|remote> --capability <id[@version]> [--capability <...>] [--reason <text>]",
      "  tyrum-cli pairing deny --pairing-id <id> [--reason <text>]",
      "  tyrum-cli pairing revoke --pairing-id <id> [--reason <text>]",
      "  tyrum-cli secrets list",
      "  tyrum-cli secrets store --secret-key <secret_key> --value <value>",
      "  tyrum-cli secrets revoke --handle-id <handle-id>",
      "  tyrum-cli secrets rotate --handle-id <handle-id> --value <value>",
      "  tyrum-cli policy bundle",
      "  tyrum-cli policy overrides list",
      "  tyrum-cli policy overrides create --agent-id <agent-id> --tool-id <tool-id> --pattern <glob> [--workspace-id <workspace-id>]",
      "  tyrum-cli policy overrides revoke --policy-override-id <id> [--reason <text>]",
      "",
      "Notes:",
      "  - policy/* and secrets/* are admin-only surfaces and require Elevated Mode (see `tyrum-cli elevated-mode enter`) or an explicit `--elevated-token <token>`.",
      "",
      "Environment:",
      "  TYRUM_HOME  Defaults to ~/.tyrum",
    ].join("\n"),
  );
}
