import { z } from "zod";
import {
  WsApprovalListRequest,
  WsApprovalResolveRequest,
  WsApprovalUpdatedEvent,
} from "./approvals.js";
import { WsCapabilityReadyEvent, WsCapabilityReadyRequest } from "./capability-ready.js";
import {
  WsConnectInitRequest,
  WsConnectProofRequest,
  WsConnectRequest,
  WsPingRequest,
} from "./connect.js";
import {
  WsArtifactAttachedEvent,
  WsArtifactCreatedEvent,
  WsArtifactFetchedEvent,
  WsAttemptEvidenceEvent,
  WsAttemptEvidenceRequest,
  WsAttemptUpdatedEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsChannelQueueOverflowEvent,
  WsContextReportCreatedEvent,
  WsErrorEvent,
  WsPlanUpdateEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPolicyOverrideRevokedEvent,
  WsProviderUsagePolledEvent,
  WsRoutingConfigUpdatedEvent,
  WsTurnBlockedEvent,
  WsTurnCancelledEvent,
  WsTurnCompletedEvent,
  WsTurnFailedEvent,
  WsTurnListRequest,
  WsTurnQueuedEvent,
  WsTurnResumedEvent,
  WsTurnStartedEvent,
  WsToolLifecycleEvent,
  WsTurnUpdatedEvent,
  WsStepUpdatedEvent,
  WsTaskExecuteRequest,
  WsUsageSnapshotEvent,
} from "./execution.js";
import {
  WsPairingApproveRequest,
  WsPairingDenyRequest,
  WsPairingUpdatedEvent,
  WsPairingRevokeRequest,
} from "./pairing.js";
import { WsLocationBeaconRequest } from "./location.js";
import {
  WsPresenceBeaconRequest,
  WsPresencePrunedEvent,
  WsPresenceUpsertedEvent,
} from "./presence.js";
import { WsCommandExecuteRequest } from "./command-execute.js";
import {
  WsDeliveryReceiptEvent,
  WsFormattingFallbackEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsReasoningDeltaEvent,
  WsReasoningFinalEvent,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
} from "./chat-events.js";
import {
  WsAiSdkChatStreamEvent,
  WsConversationArchiveRequest,
  WsConversationCreateRequest,
  WsConversationDeleteRequest,
  WsConversationGetRequest,
  WsConversationListRequest,
  WsConversationQueueModeSetRequest,
  WsConversationReconnectRequest,
  WsConversationSendRequest,
} from "./chat-conversation.js";
import {
  WsSubagentCloseRequest,
  WsSubagentClosedEvent,
  WsSubagentGetRequest,
  WsSubagentListRequest,
  WsSubagentOutputEvent,
  WsSubagentSendRequest,
  WsSubagentSpawnedEvent,
  WsSubagentSpawnRequest,
  WsSubagentUpdatedEvent,
} from "./subagent.js";
import { WsTranscriptGetRequest, WsTranscriptListRequest } from "./transcript.js";
import { WsResponse } from "./unions-response.js";
import {
  WsWorkflowCancelRequest,
  WsWorkflowResumeRequest,
  WsWorkflowStartRequest,
} from "./workflow.js";
import {
  WsWorkArtifactCreateRequest,
  WsWorkArtifactCreatedEvent,
  WsWorkArtifactGetRequest,
  WsWorkArtifactListRequest,
  WsWorkCreateRequest,
  WsWorkDeleteRequest,
  WsWorkDecisionCreateRequest,
  WsWorkDecisionCreatedEvent,
  WsWorkDecisionGetRequest,
  WsWorkDecisionListRequest,
  WsWorkGetRequest,
  WsWorkItemBlockedEvent,
  WsWorkItemCancelledEvent,
  WsWorkItemCompletedEvent,
  WsWorkItemDeletedEvent,
  WsWorkItemFailedEvent,
  WsWorkItemCreatedEvent,
  WsWorkItemUpdatedEvent,
  WsWorkLinkCreateRequest,
  WsWorkLinkCreatedEvent,
  WsWorkLinkListRequest,
  WsWorkListRequest,
  WsWorkSignalCreateRequest,
  WsWorkSignalCreatedEvent,
  WsWorkSignalUpdatedEvent,
  WsWorkSignalFiredEvent,
  WsWorkSignalGetRequest,
  WsWorkSignalListRequest,
  WsWorkSignalUpdateRequest,
  WsWorkStateKvGetRequest,
  WsWorkStateKvListRequest,
  WsWorkStateKvSetRequest,
  WsWorkStateKvUpdatedEvent,
  WsWorkTaskCancelledEvent,
  WsWorkTaskCompletedEvent,
  WsWorkTaskFailedEvent,
  WsWorkTaskLeasedEvent,
  WsWorkTaskPausedEvent,
  WsWorkTaskStartedEvent,
  WsWorkPauseRequest,
  WsWorkResumeRequest,
  WsWorkTransitionRequest,
  WsWorkUpdateRequest,
} from "./work.js";

export * from "./unions-response.js";

export const WsRequest = z.discriminatedUnion("type", [
  WsConnectInitRequest,
  WsConnectProofRequest,
  WsConnectRequest,
  WsLocationBeaconRequest,
  WsPresenceBeaconRequest,
  WsPingRequest,
  WsConversationListRequest,
  WsConversationGetRequest,
  WsConversationCreateRequest,
  WsConversationDeleteRequest,
  WsConversationArchiveRequest,
  WsConversationQueueModeSetRequest,
  WsConversationReconnectRequest,
  WsConversationSendRequest,
  WsCommandExecuteRequest,
  WsWorkflowStartRequest,
  WsWorkflowResumeRequest,
  WsWorkflowCancelRequest,
  WsPairingRevokeRequest,
  WsPairingApproveRequest,
  WsPairingDenyRequest,
  WsCapabilityReadyRequest,
  WsTaskExecuteRequest,
  WsAttemptEvidenceRequest,
  WsTurnListRequest,
  WsApprovalListRequest,
  WsApprovalResolveRequest,
  WsSubagentSpawnRequest,
  WsTranscriptListRequest,
  WsTranscriptGetRequest,
  WsSubagentListRequest,
  WsSubagentGetRequest,
  WsSubagentSendRequest,
  WsSubagentCloseRequest,
  WsWorkListRequest,
  WsWorkGetRequest,
  WsWorkCreateRequest,
  WsWorkUpdateRequest,
  WsWorkDeleteRequest,
  WsWorkTransitionRequest,
  WsWorkPauseRequest,
  WsWorkResumeRequest,
  WsWorkLinkCreateRequest,
  WsWorkLinkListRequest,
  WsWorkArtifactListRequest,
  WsWorkArtifactGetRequest,
  WsWorkArtifactCreateRequest,
  WsWorkDecisionListRequest,
  WsWorkDecisionGetRequest,
  WsWorkDecisionCreateRequest,
  WsWorkSignalListRequest,
  WsWorkSignalGetRequest,
  WsWorkSignalCreateRequest,
  WsWorkSignalUpdateRequest,
  WsWorkStateKvGetRequest,
  WsWorkStateKvListRequest,
  WsWorkStateKvSetRequest,
]);
export type WsRequest = z.infer<typeof WsRequest>;

export const WsEvent = z.discriminatedUnion("type", [
  WsPlanUpdateEvent,
  WsAuthFailedEvent,
  WsAuthzDeniedEvent,
  WsApprovalUpdatedEvent,
  WsTurnUpdatedEvent,
  WsTurnQueuedEvent,
  WsTurnStartedEvent,
  WsTurnBlockedEvent,
  WsTurnResumedEvent,
  WsTurnCompletedEvent,
  WsTurnFailedEvent,
  WsTurnCancelledEvent,
  WsStepUpdatedEvent,
  WsAttemptUpdatedEvent,
  WsArtifactCreatedEvent,
  WsArtifactAttachedEvent,
  WsArtifactFetchedEvent,
  WsCapabilityReadyEvent,
  WsAttemptEvidenceEvent,
  WsPairingUpdatedEvent,
  WsPresenceUpsertedEvent,
  WsPresencePrunedEvent,
  WsPolicyOverrideCreatedEvent,
  WsPolicyOverrideRevokedEvent,
  WsPolicyOverrideExpiredEvent,
  WsPluginLifecycleEvent,
  WsPluginToolInvokedEvent,
  WsToolLifecycleEvent,
  WsChannelQueueOverflowEvent,
  WsTypingStartedEvent,
  WsTypingStoppedEvent,
  WsAiSdkChatStreamEvent,
  WsMessageDeltaEvent,
  WsMessageFinalEvent,
  WsReasoningDeltaEvent,
  WsReasoningFinalEvent,
  WsFormattingFallbackEvent,
  WsDeliveryReceiptEvent,
  WsUsageSnapshotEvent,
  WsProviderUsagePolledEvent,
  WsContextReportCreatedEvent,
  WsRoutingConfigUpdatedEvent,
  WsWorkItemCreatedEvent,
  WsWorkItemUpdatedEvent,
  WsWorkItemBlockedEvent,
  WsWorkItemCompletedEvent,
  WsWorkItemFailedEvent,
  WsWorkItemCancelledEvent,
  WsWorkItemDeletedEvent,
  WsWorkLinkCreatedEvent,
  WsWorkTaskLeasedEvent,
  WsWorkTaskStartedEvent,
  WsWorkTaskPausedEvent,
  WsWorkTaskCompletedEvent,
  WsWorkTaskFailedEvent,
  WsWorkTaskCancelledEvent,
  WsWorkArtifactCreatedEvent,
  WsWorkDecisionCreatedEvent,
  WsWorkSignalCreatedEvent,
  WsWorkSignalUpdatedEvent,
  WsWorkSignalFiredEvent,
  WsWorkStateKvUpdatedEvent,
  WsSubagentSpawnedEvent,
  WsSubagentUpdatedEvent,
  WsSubagentClosedEvent,
  WsSubagentOutputEvent,
  WsErrorEvent,
]);
export type WsEvent = z.infer<typeof WsEvent>;

export const WsMessage = z.union([WsRequest, WsResponse, WsEvent]);
export type WsMessage = z.infer<typeof WsMessage>;
