import { z } from "zod";
import {
  WsApprovalListResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalResolveResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
} from "./approvals.js";
import {
  WsCapabilityReadyResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
} from "./capability-ready.js";
import {
  WsConnectInitResponseErrEnvelope,
  WsConnectInitResponseOkEnvelope,
  WsConnectProofResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsPingResponseErrEnvelope,
  WsPingResponseOkEnvelope,
} from "./connect.js";
import {
  WsAttemptEvidenceResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsRunListResponseErrEnvelope,
  WsRunListResponseOkEnvelope,
  WsTaskExecuteResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
} from "./execution.js";
import {
  WsPairingApproveResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingDenyResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingRevokeResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
} from "./pairing.js";
import {
  WsLocationBeaconResponseErrEnvelope,
  WsLocationBeaconResponseOkEnvelope,
} from "./location.js";
import {
  WsPresenceBeaconResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
} from "./presence.js";
import {
  WsChatSessionArchiveResponseErrEnvelope,
  WsChatSessionArchiveResponseOkEnvelope,
  WsChatSessionCreateResponseErrEnvelope,
  WsChatSessionCreateResponseOkEnvelope,
  WsChatSessionDeleteResponseErrEnvelope,
  WsChatSessionDeleteResponseOkEnvelope,
  WsChatSessionGetResponseErrEnvelope,
  WsChatSessionGetResponseOkEnvelope,
  WsChatSessionListResponseErrEnvelope,
  WsChatSessionListResponseOkEnvelope,
  WsChatSessionQueueModeSetResponseErrEnvelope,
  WsChatSessionQueueModeSetResponseOkEnvelope,
  WsChatSessionReconnectResponseErrEnvelope,
  WsChatSessionReconnectResponseOkEnvelope,
  WsChatSessionSendResponseErrEnvelope,
  WsChatSessionSendResponseOkEnvelope,
} from "./chat-session.js";
import {
  WsSubagentCloseResponseErrEnvelope,
  WsSubagentCloseResponseOkEnvelope,
  WsSubagentGetResponseErrEnvelope,
  WsSubagentGetResponseOkEnvelope,
  WsSubagentListResponseErrEnvelope,
  WsSubagentListResponseOkEnvelope,
  WsSubagentSendResponseErrEnvelope,
  WsSubagentSendResponseOkEnvelope,
  WsSubagentSpawnResponseErrEnvelope,
  WsSubagentSpawnResponseOkEnvelope,
} from "./subagent.js";
import {
  WsTranscriptGetResponseErrEnvelope,
  WsTranscriptGetResponseOkEnvelope,
  WsTranscriptListResponseErrEnvelope,
  WsTranscriptListResponseOkEnvelope,
} from "./transcript.js";
import {
  WsWorkflowCancelResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
} from "./workflow.js";
import {
  WsWorkArtifactCreateResponseErrEnvelope,
  WsWorkArtifactCreateResponseOkEnvelope,
  WsWorkArtifactGetResponseErrEnvelope,
  WsWorkArtifactGetResponseOkEnvelope,
  WsWorkArtifactListResponseErrEnvelope,
  WsWorkArtifactListResponseOkEnvelope,
  WsWorkCreateResponseErrEnvelope,
  WsWorkCreateResponseOkEnvelope,
  WsWorkDeleteResponseErrEnvelope,
  WsWorkDeleteResponseOkEnvelope,
  WsWorkDecisionCreateResponseErrEnvelope,
  WsWorkDecisionCreateResponseOkEnvelope,
  WsWorkDecisionGetResponseErrEnvelope,
  WsWorkDecisionGetResponseOkEnvelope,
  WsWorkDecisionListResponseErrEnvelope,
  WsWorkDecisionListResponseOkEnvelope,
  WsWorkGetResponseErrEnvelope,
  WsWorkGetResponseOkEnvelope,
  WsWorkLinkCreateResponseErrEnvelope,
  WsWorkLinkCreateResponseOkEnvelope,
  WsWorkLinkListResponseErrEnvelope,
  WsWorkLinkListResponseOkEnvelope,
  WsWorkListResponseErrEnvelope,
  WsWorkListResponseOkEnvelope,
  WsWorkSignalCreateResponseErrEnvelope,
  WsWorkSignalCreateResponseOkEnvelope,
  WsWorkSignalGetResponseErrEnvelope,
  WsWorkSignalGetResponseOkEnvelope,
  WsWorkSignalListResponseErrEnvelope,
  WsWorkSignalListResponseOkEnvelope,
  WsWorkSignalUpdateResponseErrEnvelope,
  WsWorkSignalUpdateResponseOkEnvelope,
  WsWorkStateKvGetResponseErrEnvelope,
  WsWorkStateKvGetResponseOkEnvelope,
  WsWorkStateKvListResponseErrEnvelope,
  WsWorkStateKvListResponseOkEnvelope,
  WsWorkStateKvSetResponseErrEnvelope,
  WsWorkStateKvSetResponseOkEnvelope,
  WsWorkPauseResponseErrEnvelope,
  WsWorkPauseResponseOkEnvelope,
  WsWorkResumeResponseErrEnvelope,
  WsWorkResumeResponseOkEnvelope,
  WsWorkTransitionResponseErrEnvelope,
  WsWorkTransitionResponseOkEnvelope,
  WsWorkUpdateResponseErrEnvelope,
  WsWorkUpdateResponseOkEnvelope,
} from "./work.js";

export const WsResponse = z.union([
  WsConnectInitResponseOkEnvelope,
  WsConnectInitResponseErrEnvelope,
  WsConnectProofResponseOkEnvelope,
  WsConnectProofResponseErrEnvelope,
  WsConnectResponseOkEnvelope,
  WsConnectResponseErrEnvelope,
  WsChatSessionSendResponseOkEnvelope,
  WsChatSessionSendResponseErrEnvelope,
  WsChatSessionListResponseOkEnvelope,
  WsChatSessionListResponseErrEnvelope,
  WsChatSessionGetResponseOkEnvelope,
  WsChatSessionGetResponseErrEnvelope,
  WsChatSessionCreateResponseOkEnvelope,
  WsChatSessionCreateResponseErrEnvelope,
  WsChatSessionDeleteResponseOkEnvelope,
  WsChatSessionDeleteResponseErrEnvelope,
  WsChatSessionArchiveResponseOkEnvelope,
  WsChatSessionArchiveResponseErrEnvelope,
  WsChatSessionQueueModeSetResponseOkEnvelope,
  WsChatSessionQueueModeSetResponseErrEnvelope,
  WsChatSessionReconnectResponseOkEnvelope,
  WsChatSessionReconnectResponseErrEnvelope,
  WsWorkflowRunResponseOkEnvelope,
  WsWorkflowRunResponseErrEnvelope,
  WsWorkflowResumeResponseOkEnvelope,
  WsWorkflowResumeResponseErrEnvelope,
  WsWorkflowCancelResponseOkEnvelope,
  WsWorkflowCancelResponseErrEnvelope,
  WsPairingApproveResponseOkEnvelope,
  WsPairingApproveResponseErrEnvelope,
  WsPairingDenyResponseOkEnvelope,
  WsPairingDenyResponseErrEnvelope,
  WsPairingRevokeResponseOkEnvelope,
  WsPairingRevokeResponseErrEnvelope,
  WsLocationBeaconResponseOkEnvelope,
  WsLocationBeaconResponseErrEnvelope,
  WsPresenceBeaconResponseOkEnvelope,
  WsPresenceBeaconResponseErrEnvelope,
  WsPingResponseOkEnvelope,
  WsPingResponseErrEnvelope,
  WsCapabilityReadyResponseOkEnvelope,
  WsCapabilityReadyResponseErrEnvelope,
  WsAttemptEvidenceResponseOkEnvelope,
  WsAttemptEvidenceResponseErrEnvelope,
  WsRunListResponseOkEnvelope,
  WsRunListResponseErrEnvelope,
  WsTaskExecuteResponseOkEnvelope,
  WsTaskExecuteResponseErrEnvelope,
  WsApprovalListResponseOkEnvelope,
  WsApprovalListResponseErrEnvelope,
  WsApprovalResolveResponseOkEnvelope,
  WsApprovalResolveResponseErrEnvelope,
  WsSubagentSpawnResponseOkEnvelope,
  WsSubagentSpawnResponseErrEnvelope,
  WsTranscriptListResponseOkEnvelope,
  WsTranscriptListResponseErrEnvelope,
  WsTranscriptGetResponseOkEnvelope,
  WsTranscriptGetResponseErrEnvelope,
  WsSubagentListResponseOkEnvelope,
  WsSubagentListResponseErrEnvelope,
  WsSubagentGetResponseOkEnvelope,
  WsSubagentGetResponseErrEnvelope,
  WsSubagentSendResponseOkEnvelope,
  WsSubagentSendResponseErrEnvelope,
  WsSubagentCloseResponseOkEnvelope,
  WsSubagentCloseResponseErrEnvelope,
  WsWorkListResponseOkEnvelope,
  WsWorkListResponseErrEnvelope,
  WsWorkGetResponseOkEnvelope,
  WsWorkGetResponseErrEnvelope,
  WsWorkCreateResponseOkEnvelope,
  WsWorkCreateResponseErrEnvelope,
  WsWorkUpdateResponseOkEnvelope,
  WsWorkUpdateResponseErrEnvelope,
  WsWorkDeleteResponseOkEnvelope,
  WsWorkDeleteResponseErrEnvelope,
  WsWorkTransitionResponseOkEnvelope,
  WsWorkTransitionResponseErrEnvelope,
  WsWorkPauseResponseOkEnvelope,
  WsWorkPauseResponseErrEnvelope,
  WsWorkResumeResponseOkEnvelope,
  WsWorkResumeResponseErrEnvelope,
  WsWorkLinkCreateResponseOkEnvelope,
  WsWorkLinkCreateResponseErrEnvelope,
  WsWorkLinkListResponseOkEnvelope,
  WsWorkLinkListResponseErrEnvelope,
  WsWorkArtifactListResponseOkEnvelope,
  WsWorkArtifactListResponseErrEnvelope,
  WsWorkArtifactGetResponseOkEnvelope,
  WsWorkArtifactGetResponseErrEnvelope,
  WsWorkArtifactCreateResponseOkEnvelope,
  WsWorkArtifactCreateResponseErrEnvelope,
  WsWorkDecisionListResponseOkEnvelope,
  WsWorkDecisionListResponseErrEnvelope,
  WsWorkDecisionGetResponseOkEnvelope,
  WsWorkDecisionGetResponseErrEnvelope,
  WsWorkDecisionCreateResponseOkEnvelope,
  WsWorkDecisionCreateResponseErrEnvelope,
  WsWorkSignalListResponseOkEnvelope,
  WsWorkSignalListResponseErrEnvelope,
  WsWorkSignalGetResponseOkEnvelope,
  WsWorkSignalGetResponseErrEnvelope,
  WsWorkSignalCreateResponseOkEnvelope,
  WsWorkSignalCreateResponseErrEnvelope,
  WsWorkSignalUpdateResponseOkEnvelope,
  WsWorkSignalUpdateResponseErrEnvelope,
  WsWorkStateKvGetResponseOkEnvelope,
  WsWorkStateKvGetResponseErrEnvelope,
  WsWorkStateKvListResponseOkEnvelope,
  WsWorkStateKvListResponseErrEnvelope,
  WsWorkStateKvSetResponseOkEnvelope,
  WsWorkStateKvSetResponseErrEnvelope,
]);
export type WsResponse = z.infer<typeof WsResponse>;
