import { Link } from "react-router";
import { apiFetch } from "../lib/api.js";
import { useApi } from "../hooks/useApi.js";
import { formatDate } from "../lib/format.js";
import { PageHeader } from "../components/PageHeader.js";
import { Card } from "../components/Card.js";
import { LoadingSpinner } from "../components/LoadingSpinner.js";

interface CanvasArtifact {
  id: string;
  title: string;
  content_type: string;
  created_at: string;
}

export function CanvasList() {
  const { data, error, loading } = useApi<CanvasArtifact[]>(
    () => apiFetch<CanvasArtifact[]>("/canvas?limit=100"),
    [],
  );

  if (loading) return <LoadingSpinner />;
  if (error) return <p className="notice error">{error.message}</p>;

  return (
    <>
      <PageHeader title="Canvas" subtitle="Recent canvas artifacts generated by automation runs." />
      <Card>
        <table>
          <thead>
            <tr><th>Title</th><th>ID</th><th>Type</th><th>Created</th></tr>
          </thead>
          <tbody>
            {!data || data.length === 0 ? (
              <tr><td colSpan={4} className="muted">No canvas artifacts available.</td></tr>
            ) : (
              data.map((artifact) => (
                <tr key={artifact.id}>
                  <td><Link to={`/app/canvas/${encodeURIComponent(artifact.id)}`}>{artifact.title}</Link></td>
                  <td>{artifact.id}</td>
                  <td>{artifact.content_type}</td>
                  <td>{formatDate(artifact.created_at)}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </Card>
    </>
  );
}
