{{- if not .Values.gatewayToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tyrum.fullname" . }}-gateway-token
  labels:
    {{- include "tyrum.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ default (randAlphaNum 64) .Values.gatewayToken.value | quote }}
{{- end }}

