apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyrum.fullname" . }}
  labels:
    {{- include "tyrum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "tyrum.name" . }}
    {{- if eq .Values.mode "single" }}
    app.kubernetes.io/component: all
    {{- else }}
    app.kubernetes.io/component: edge
    {{- end }}

